### ISSUE TITLE
```\Network\2 Available protocols\TCP protocol\TCP Server And Client Example .gaml``` not working

### ISSUE THREAD

**Issue by leonsi7** [gama-platform/new.gama#11]
**Describe the bug**
This model crashes when the tcp client wants to send a message. But it works when the client sends raw message :
```
do connect to: "localhost" protocol: "tcp_client" port: 3001 with_name: name  raw:true;
```
instead of 
```
do connect to: "localhost" protocol: "tcp_client" port: 3001 with_name: name;
```
However, the model ```Network\2 Available protocols\TCP protocol\TCP Teleportation.gaml``` works

**Desktop (please complete the following information):**
 - OS: Windows 11

**Comment by lesquoyb** [comment]
The example model I gave is still broken but differently, it runs until step 32 (on my computer) then raises an illegal argument exception:
```
Caused by: java.nio.file.InvalidPathException: Illegal char <> at index 0: 
at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:191)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:142)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:46)
	at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
	at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:203)
	at java.base/java.nio.file.Path.of(Path.java:148)
	at java.base/java.nio.file.Paths.get(Paths.java:69)
	at gama.api.utils.files.FileUtils.isAbsolutePath(FileUtils.java:144)
	at gama.api.utils.files.FileUtils.resolveAbsoluteFilePath(FileUtils.java:205)
	at gama.api.utils.files.FileUtils.constructAbsoluteFilePath(FileUtils.java:181)
	at gama.extension.serialize.binary.BinarySerialisation.createFromFile(BinarySerialisation.java:57)
	at gama.extension.serialize.binary.BinarySerialisation.createFromString(BinarySerialisation.java:81)
	... 11 more
java.lang.InterruptedException
	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1140)
	at java.base/java.util.concurrent.Semaphore.acquire(Semaphore.java:475)
	at gama.api.runtime.GeneralSynchronizer.acquire(GeneralSynchronizer.java:218)
	at gama.api.runtime.SimulationRunner.step(SimulationRunner.java:240)
	at gama.core.simulation.SimulationPopulation.stepAgents(SimulationPopulation.java:271)
	at gama.core.population.AbstractPopulation.step(AbstractPopulation.java:407)
	at gama.api.runtime.scope.ExecutionScope.step(ExecutionScope.java:775)
	at gama.core.agent.GamlAgent.stepSubPopulations(GamlAgent.java:120)
	at gama.core.agent.MinimalAgent._step_(MinimalAgent.java:345)
	at gama.core.agent.MinimalAgent.doStep(MinimalAgent.java:314)
	at gama.core.agent.MinimalAgent.step(MinimalAgent.java:688)
	at gama.api.runtime.scope.ExecutionScope.step(ExecutionScope.java:809)
	at gama.api.kernel.simulation.DefaultExperimentController.step(DefaultExperimentController.java:613)
	at gama.api.kernel.simulation.DefaultExperimentController.lambda$0(DefaultExperimentController.java:205)
	at java.base/java.lang.Thread.run(Thread.java:1474)
```
